services:
  back-end:
    image: back-session7
    depends_on: 
      - database
    build:
      context: .  
      dockerfile: Dockerfile
    environment:
       MONGO_URI: mongodb://root:example@database:27017/book-store?authSource=admin
       PORT: 3002
    ports:
      - "4000:3002"
    container_name: back-container
    
  database:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    depends_on: 
      - database
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/
      ME_CONFIG_BASICAUTH: false


      